# Generated by Django 5.2.8 on 2025-11-29 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_covered', models.BooleanField(default=False, verbose_name='Techada')),
                ('has_lighting', models.BooleanField(default=True, verbose_name='Tiene iluminación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='courts.court', verbose_name='Cancha')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'ordering': ['court', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CourtSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('opening_time', models.TimeField(verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(verbose_name='Hora de cierre')),
                ('slot_duration', models.IntegerField(default=60, verbose_name='Duración del turno (minutos)')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courts.court', verbose_name='Cancha')),
            ],
            options={
                'verbose_name': 'Horario de cancha',
                'verbose_name_plural': 'Horarios de canchas',
                'ordering': ['court', 'day_of_week', 'opening_time'],
                'unique_together': {('court', 'day_of_week')},
            },
        ),
    ]
